version: "3.9"

services:
  db:
    image: "postgres:latest"
    container_name: "typeOrm_db"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    